# Generated by Django 3.0.3 on 2020-02-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(default='Тема', max_length=200),
        ),
        migrations.AddField(
            model_name='entry',
            name='url',
            field=models.URLField(default='a'),
        ),
        migrations.AddField(
            model_name='entry',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
