# Generated by Django 3.0.3 on 2020-02-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0004_auto_20200226_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
